<?php
declare(strict_types=1);

// FakeRest SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

FakeRestUtility::setRegistrar(function (FakeRestUtility $u): void {
    $u->clean = [FakeRestClean::class, 'call'];
    $u->done = [FakeRestDone::class, 'call'];
    $u->make_error = [FakeRestMakeError::class, 'call'];
    $u->feature_add = [FakeRestFeatureAdd::class, 'call'];
    $u->feature_hook = [FakeRestFeatureHook::class, 'call'];
    $u->feature_init = [FakeRestFeatureInit::class, 'call'];
    $u->fetcher = [FakeRestFetcher::class, 'call'];
    $u->make_fetch_def = [FakeRestMakeFetchDef::class, 'call'];
    $u->make_context = [FakeRestMakeContext::class, 'call'];
    $u->make_options = [FakeRestMakeOptions::class, 'call'];
    $u->make_request = [FakeRestMakeRequest::class, 'call'];
    $u->make_response = [FakeRestMakeResponse::class, 'call'];
    $u->make_result = [FakeRestMakeResult::class, 'call'];
    $u->make_point = [FakeRestMakePoint::class, 'call'];
    $u->make_spec = [FakeRestMakeSpec::class, 'call'];
    $u->make_url = [FakeRestMakeUrl::class, 'call'];
    $u->param = [FakeRestParam::class, 'call'];
    $u->prepare_auth = [FakeRestPrepareAuth::class, 'call'];
    $u->prepare_body = [FakeRestPrepareBody::class, 'call'];
    $u->prepare_headers = [FakeRestPrepareHeaders::class, 'call'];
    $u->prepare_method = [FakeRestPrepareMethod::class, 'call'];
    $u->prepare_params = [FakeRestPrepareParams::class, 'call'];
    $u->prepare_path = [FakeRestPreparePath::class, 'call'];
    $u->prepare_query = [FakeRestPrepareQuery::class, 'call'];
    $u->graphql_body = [FakeRestGraphql::class, 'body'];
    $u->graphql_errors = [FakeRestGraphql::class, 'errors'];
    $u->result_basic = [FakeRestResultBasic::class, 'call'];
    $u->result_body = [FakeRestResultBody::class, 'call'];
    $u->result_headers = [FakeRestResultHeaders::class, 'call'];
    $u->transform_request = [FakeRestTransformRequest::class, 'call'];
    $u->transform_response = [FakeRestTransformResponse::class, 'call'];
});
